/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AMLRuntimeModule extends AbstractAMLRuntimeModule {
}
