/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AMLStandaloneSetup extends AMLStandaloneSetupGenerated {

	def static void doSetup() {
		new AMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
