/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class AMLIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new AMLStandaloneSetupIdea().createInjector
	}

}
