/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class AMLIdeaModule extends AbstractAMLIdeaModule {
}
