/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper.idea.lang


class AMLFileType extends AbstractAMLFileType {
	public static final AMLFileType INSTANCE = new AMLFileType()
	
	new() {
		super(AMLLanguage.INSTANCE)
	}
}
