/*
 * generated by Xtext 2.9.2
 */
package pl.adrian.pieper.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import pl.adrian.pieper.idea.lang.AMLLanguage

class AMLCompletionContributor extends AbstractAMLCompletionContributor {
	new() {
		this(AMLLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
